import type { Metadata } from "next";
import { Playfair_Display,Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
const play_fair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--play_fair',
})
 



export const metadata: Metadata = {
  title: "Groves",
  description: "Generated by Faizan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${play_fair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
